export const languages = {
  ka: {
    price: "ფასი",
    from: "დან",
    to: "მდე",
    mostwanted: "ყველაზე მოთხოვნადი",
    allproducts: "ყველა ინსტრუმენტი",
    midderhero: "ბაღის ინვენტარი",
    bestbrands: "მსოფლიოს საუკეთესო ბრენდები",
    delivery: "მიწოდება",
    delivery2: "100₾+ შეკვეთაზე მოქმედებს უფასო მიწოდების სერვისი",
    quality: "ხარისხი",
    quality2: "ყველა პროდუქტი არის უმაღლესი ხარისხის",
    guarantee: "გარანტია",
    guarantee2: "ყველა პროდუქტი არის საწარმოს გარანტიაზე",
  },
  ru: {
    price: "Цена",
    from: "от",
    to: "до",
    mostwanted: "самый востребованный",
    allproducts: "Все инструменты",
    midderhero: "Садовый инвентарь",
    bestbrands: "Лучшие мировые бренды",
    delivery: "доставка",
    delivery2: "Услуга бесплатной доставки распространяется на заказы от 100₾",
    quality: "качество",
    quality2: "Все товары высшего качества",
    guarantee: "Гарантия",
    guarantee2: "Все товары находятся на заводской гарантии",
  },
  en: {
    price: "Price",
    from: "From",
    to: "To",
    mostwanted: "most requested",
    allproducts: "All tools",
    midderhero: "Garden inventory",
    bestbrands: "The world's best brands",
    delivery: "მიწოდება",
    delivery2: "100₾+ შეკვეთაზე მოქმედებს უფასო მიწოდების სერვისი",
    quality: "ხარისხი",
    quality2: "ყველა პროდუქტი არის უმაღლესი ხარისხის",
    guarantee: "გარანტია",
    guarantee2: "ყველა პროდუქტი არის საწარმოს გარანტიაზე",
  },
};
