export const languages = {
  ka: {
    price: "ფასი",
    from: "დან",
    to: "მდე",
    mostwanted: "ყველაზე მოთხოვნადი",
    allproducts: "ყველა ინსტრუმენტი",
    midderhero: "ბაღის ინვენტარი",
    bestbrands: "მსოფლიოს საუკეთესო ბრენდები",
    delivery: "მიწოდება",
    delivery2: "100₾+ შეკვეთაზე მოქმედებს უფასო მიწოდების სერვისი",
    quality: "ხარისხი",
    quality2: "ყველა პროდუქტი არის უმაღლესი ხარისხის",
    guarantee: "გარანტია",
    guarantee2: "ყველა პროდუქტი არის საწარმოს გარანტიაზე",
    add: "დამატება",
    promo:
      "აქ თქვენ შეგიძლიათ იქირაოთ ნებისმიერი თქვენითვის საჭირო ხელსაწყო რამდენი ხნითაც გნებავთ",
    lang: "ენა",
    currency: "ვალუტა",
    dollar: "დოლარი",
    lari: "ლარი",
    geo: "ქართული",
    eng: "ინგლისური",
    rus: "რუსული",
    menu: {
      home: "მთავარი",
      tools: {
        main: "ინსტრუმენტები",
        electric: "ელექტრო ინსტრუმენტები",
        build: "სამშენებლო მოწყობილობები",
        cleaning: "საწმენდი ტექნიკა",
        paint: "სამღებრო ინსტრუმენტები",
        handtools: "ხელის ინსტრუმენტები",
      },
      homeandgarden: {
        main: "სახლი და ეზო",
        garden: "ბაღის მოვლა",
        water: "საწრავი მილები",
        box: "ინსტრუმენტების ყუთები",
        gardenfurn: "ბაღის ჭურჭელი",
      },
      auto: {
        main: "ავტო ტექნიკა",
        manipulator: "ამწე მანიპულატორი",
        tvitmcleli: "თვითმცლელი",
        trailer: "ტრაილერი",
      },
      about: "ჩვენს შესახებ",
      policy: "პირობები",
      contact: "კონტაქტი",
    },
  },
  ru: {
    price: "Цена",
    from: "от",
    to: "до",
    mostwanted: "самый востребованный",
    allproducts: "Все инструменты",
    midderhero: "Садовый инвентарь",
    bestbrands: "Лучшие мировые бренды",
    delivery: "доставка",
    delivery2: "Услуга бесплатной доставки распространяется на заказы от 100₾",
    quality: "качество",
    quality2: "Все товары высшего качества",
    guarantee: "Гарантия",
    guarantee2: "Все товары находятся на заводской гарантии",
    add: "добавить",
    promo:
      "Здесь вы можете арендовать любое необходимое оборудование на любой срок.",
    lang: "язык",
    currency: "валюта",
    dollar: "Доллар",
    lari: "Лари",
    geo: "Грузинский",
    eng: "Английский",
    rus: "Русский",
    menu: {
      home: "главная",
      tools: {
        main: "инструменты",
        electric: "электроинструменты",
        build: "Строительные инструменты",
        cleaning: "уборочное оборудование",
        paint: "малярные инструменты",
        handtools: "ручные инструменты",
      },
      homeandgarden: {
        main: "дом и двор",
        garden: "уход за садом",
        water: "водопроводные трубы",
        box: "ящики для инструментов",
        gardenfurn: "садовая мебель",
      },
      auto: {
        main: "автотехника",
        manipulator: "кран-манипулятор",
        tvitmcleli: "самоотверженный",
        trailer: "Трейлер",
      },
      about: "О нас",
      policy: "термины",
      contact: "Контакты",
    },
  },
  en: {
    price: "Price",
    from: "From",
    to: "To",
    mostwanted: "most requested",
    allproducts: "All tools",
    midderhero: "Garden inventory",
    bestbrands: "The world's best brands",
    delivery: "delivery",
    delivery2: "Free delivery service applies to orders of 100₾+",
    quality: "quality",
    quality2: "All products are of the highest quality",
    guarantee: "Guarantee",
    guarantee2: "All products are under factory warranty",
    add: "Add",
    promo: "Here you can rent any equipment you need for as long as you want",
    lang: "language",
    currency: "currency",
    dollar: "Dollar",
    lari: "Lari",
    geo: "Georgian",
    eng: "English",
    rus: "Russian",
    menu: {
      home: "main",
      tools: {
        main: "tools",
        electric: "electrical instruments",
        build: "Construction Tools",
        cleaning: "cleaning equipment",
        paint: "painting tools",
        handtools: "hand tools",
      },
      homeandgarden: {
        main: "house and yard",
        garden: "garden care",
        water: "water pipes",
        box: "tool boxes",
        gardenfurn: "garden furniture",
      },
      auto: {
        main: "auto equipment",
        manipulator: "crane manipulator",
        tvitmcleli: "Truck",
        trailer: "Trailer",
      },
      about: "About us",
      policy: "terms",
      contact: "contact",
    },
  },
};
