export const languages = {
  ka: {
    price: "ფასი",
    from: "დან",
    to: "მდე",
    mostwanted: "ყველაზე მოთხოვნადი",
    allproducts: "ყველა ინსტრუმენტი",
    midderhero: "ბაღის ინვენტარი",
    bestbrands: "მსოფლიოს საუკეთესო ბრენდები",
    delivery: "მიწოდება",
    delivery2: "100₾+ შეკვეთაზე მოქმედებს უფასო მიწოდების სერვისი",
    quality: "ხარისხი",
    quality2: "ყველა პროდუქტი არის უმაღლესი ხარისხის",
    guarantee: "გარანტია",
    guarantee2: "ყველა პროდუქტი არის საწარმოს გარანტიაზე",
    add: "დამატება",
    promo:
      "აქ თქვენ შეგიძლიათ იქირაოთ ნებისმიერი თქვენითვის საჭირო ხელსაწყო რამდენი ხნითაც გნებავთ",
    lang: "ენა",
    currency: "ვალუტა",
    dollar: "დოლარი",
    lari: "ლარი",
    geo: "ქართული",
    eng: "ინგლისური",
    rus: "რუსული",
    nav: "ნავიგაცია",
    menu: {
      home: "მთავარი",
      tools: {
        main: "ინსტრუმენტები",
        electric: "ელექტრო ინსტრუმენტები",
        build: "სამშენებლო მოწყობილობები",
        cleaning: "საწმენდი ტექნიკა",
        paint: "სამღებრო ინსტრუმენტები",
        handtools: "ხელის ინსტრუმენტები",
      },
      homeandgarden: {
        main: "სახლი და ეზო",
        garden: "ბაღის მოვლა",
        water: "საწრავი მილები",
        box: "ინსტრუმენტების ყუთები",
        gardenfurn: "ბაღის ჭურჭელი",
      },
      auto: {
        main: "ავტო ტექნიკა",
        manipulator: "ამწე მანიპულატორი",
        tvitmcleli: "თვითმცლელი",
        trailer: "ტრაილერი",
      },
      about: "ჩვენს შესახებ",
      policy: "პირობები",
      contact: "კონტაქტი",
    },
  },
  ru: {
    price: "Цена",
    from: "от",
    to: "до",
    mostwanted: "самый востребованный",
    allproducts: "Все инструменты",
    midderhero: "Садовый инвентарь",
    bestbrands: "Лучшие мировые бренды",
    delivery: "доставка",
    delivery2: "Услуга бесплатной доставки распространяется на заказы от 100₾",
    quality: "качество",
    quality2: "Все товары высшего качества",
    guarantee: "Гарантия",
    guarantee2: "Все товары находятся на заводской гарантии",
    add: "добавить",
    promo:
      "Здесь вы можете арендовать любое необходимое оборудование на любой срок.",
    lang: "язык",
    currency: "валюта",
    dollar: "Доллар",
    lari: "Лари",
    geo: "Грузинский",
    eng: "Английский",
    rus: "Русский",
    nav: "Навигация",
    menu: {
      home: "Главная",
      tools: {
        main: "Инструменты",
        electric: "Электроинструменты",
        build: "Строительные Инструменты",
        cleaning: "Уборочное Оборудование",
        paint: "Малярные Инструменты",
        handtools: "Ручные Инструменты",
      },
      homeandgarden: {
        main: "Дом и Двор",
        garden: "Уход за Садом",
        water: "Водопроводные Трубы",
        box: "Ящики для Инструментов",
        gardenfurn: "Садовая Мебель",
      },
      auto: {
        main: "Автотехника",
        manipulator: "Кран-Манипулятор",
        tvitmcleli: "Самоотверженный",
        trailer: "Трейлер",
      },
      about: "О нас",
      policy: "Термины",
      contact: "Контакты",
    },
  },
  en: {
    price: "Price",
    from: "From",
    to: "To",
    mostwanted: "most requested",
    allproducts: "All tools",
    midderhero: "Garden inventory",
    bestbrands: "The world's best brands",
    delivery: "delivery",
    delivery2: "Free delivery service applies to orders of 100₾+",
    quality: "quality",
    quality2: "All products are of the highest quality",
    guarantee: "Guarantee",
    guarantee2: "All products are under factory warranty",
    add: "Add",
    promo: "Here you can rent any equipment you need for as long as you want",
    lang: "language",
    currency: "currency",
    dollar: "Dollar",
    lari: "Lari",
    geo: "Georgian",
    eng: "English",
    rus: "Russian",
    nav: "Navigation",
    menu: {
      home: "Main",
      tools: {
        main: "Tools",
        electric: "Electrical Instruments",
        build: "Construction Tools",
        cleaning: "Cleaning Equipment",
        paint: "Painting Tools",
        handtools: "Hand Tools",
      },
      homeandgarden: {
        main: "House and Yard",
        garden: "Garden Care",
        water: "Water Pipes",
        box: "Tool Boxes",
        gardenfurn: "Barden Furniture",
      },
      auto: {
        main: "Auto Equipment",
        manipulator: "Crane Manipulator",
        tvitmcleli: "Truck",
        trailer: "Trailer",
      },
      about: "About us",
      policy: "Terms",
      contact: "Contact",
    },
  },
};
